spring:
  datasource:
    url: jdbc:mysql://10.138.52.84:8306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: '!@#$PwdIsSecret'
  elasticsearch:
    uris: 10.138.52.84:9200
logging:
  level:
    root: info
    com.macro.mall: debug
logstash:
  host: localhost
